import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { AGENTS_HOME, HARNESS_ROOT, HARNESS_RULES_DIR } from './agentsLayout.js';

const GENERATED_MARKER = '<!-- harness-agents-md: generated by @nextstage-brasil/harness agents-md -->';
const SYNC_MANAGED_DEFAULT = '<!-- harness-sync-managed: last-sync=never -->';

const SDD_PLANNING = [
  'clarify-requirements',
  'requirements-generator',
  'analyze-consistency',
  'version-partitioner',
  'task-generator',
  'execution-handoff-generator',
  'unit-test-task-generator',
  'e2e-test-generator',
];

const IMPL_SKILLS = ['coder', 'execute-gitlab-issue', 'execution-orchestrator'];
const CLOSE_SKILLS = ['code-reviewer', 'living-spec-consolidator'];

const LAYOUT_PATHS = [
  { path: 'AGENTS.md', purpose: 'Project rules entry point' },
  { path: HARNESS_RULES_DIR, purpose: 'Canonical project rules' },
  { path: join(HARNESS_ROOT, 'manifest.json'), purpose: 'Adapter config for harness sync' },
  { path: '.cursor/rules/', purpose: 'Generated Cursor rule adapters' },
  { path: '.claude/rules/', purpose: 'Generated Claude rule adapters' },
  { path: join(AGENTS_HOME, 'skills/'), purpose: 'Installed skills (Skills CLI)' },
  { path: join(AGENTS_HOME, 'agents/'), purpose: 'Agent personas (canonical)' },
  { path: '.cursor/agents/', purpose: 'Symlinked Cursor subagents' },
  { path: '.claude/agents/', purpose: 'Symlinked Claude Code subagents' },
  { path: join(AGENTS_HOME, 'docs/'), purpose: 'Agent-oriented project docs' },
  { path: 'docs/context/', purpose: 'Product context (stack, brownfield)' },
  { path: 'docs/versions/', purpose: 'SDD version artifacts' },
  { path: 'docs/specs/', purpose: 'Living domain specs' },
];

function listSkillDirs(projectRoot) {
  const skillsDir = join(projectRoot, AGENTS_HOME, 'skills');
  if (!existsSync(skillsDir)) return [];
  return readdirSync(skillsDir)
    .filter((entry) => {
      const path = join(skillsDir, entry);
      return statSync(path).isDirectory();
    })
    .sort();
}

function listPersonas(projectRoot) {
  const personasDir = join(projectRoot, AGENTS_HOME, 'agents');
  if (!existsSync(personasDir)) return [];
  return readdirSync(personasDir)
    .filter((entry) => entry.endsWith('.md'))
    .map((entry) => entry.replace(/\.md$/, ''))
    .sort();
}

function pathExists(projectRoot, relPath) {
  return existsSync(join(projectRoot, relPath));
}

function readProjectTitle(projectRoot) {
  const readmePath = join(projectRoot, 'README.md');
  if (existsSync(readmePath)) {
    const firstLine = readFileSync(readmePath, 'utf8').split('\n').find((l) => l.trim());
    if (firstLine?.startsWith('# ')) {
      return firstLine.slice(2).trim();
    }
  }
  return basename(resolve(projectRoot));
}

function buildSddChain(installed) {
  const set = new Set(installed);
  const parts = SDD_PLANNING.filter((skill) => set.has(skill));
  const impl = IMPL_SKILLS.filter((skill) => set.has(skill));
  if (impl.length > 0) {
    parts.push(`implementation (\`${impl.join('` / `')}\`)`);
  }
  parts.push(...CLOSE_SKILLS.filter((skill) => set.has(skill)));
  return parts.length > 0 ? parts.map((p) => `\`${p}\``).join(' → ') : '_No SDD planning skills installed._';
}

function buildImplementationNote(installed) {
  const set = new Set(installed);
  if (set.has('execute-gitlab-issue')) {
    return 'GitLab issues → `execute-gitlab-issue` (+ `code-reviewer` gate when installed).';
  }
  if (set.has('execution-orchestrator')) {
    return 'Partitioned versions → `execution-orchestrator` (slice-by-slice).';
  }
  if (set.has('coder')) {
    return 'Ad-hoc tasks → `coder` or persona `code-coder`.';
  }
  return '_No implementation skills installed._';
}

function preserveSyncManaged(existingContent) {
  const match = existingContent?.match(/<!-- harness-sync-managed: last-sync=[^>]+ -->/);
  return match?.[0] ?? SYNC_MANAGED_DEFAULT;
}

function isGeneratedOrStub(content) {
  if (!content) return true;
  return (
    content.includes(GENERATED_MARKER)
    || content.includes('Replace this stub by running the `architecture-rules-generator` skill')
    || content.includes('Typical SDD chain')
  );
}

export function generateAgentsMd(projectRoot, options = {}) {
  const { force = false } = options;
  const root = resolve(projectRoot);
  const agentsPath = join(root, 'AGENTS.md');
  const claudePath = join(root, 'CLAUDE.md');

  const installed = listSkillDirs(root);
  if (installed.length === 0) {
    throw new Error('No skills in .agents/skills/ — run harness init first');
  }

  if (existsSync(agentsPath) && !force) {
    const existing = readFileSync(agentsPath, 'utf8');
    if (!isGeneratedOrStub(existing)) {
      return { skipped: true, reason: 'AGENTS.md exists (use --force to overwrite)' };
    }
  }

  const personas = listPersonas(root);
  const projectName = readProjectTitle(root);
  const harnessRoot = `${HARNESS_ROOT}/`;
  const syncManaged = preserveSyncManaged(
    existsSync(agentsPath) ? readFileSync(agentsPath, 'utf8') : '',
  );

  const layoutRows = LAYOUT_PATHS.map(({ path, purpose }) => {
    const present = pathExists(root, path);
    return `| \`${path}\` | ${purpose} | ${present ? 'present' : 'not present'} |`;
  });

  const skillsList = installed.map((skill) => `- \`${skill}\``).join('\n');
  const personasBlock =
    personas.length > 0
      ? personas.map((name) => `- \`${name}\` — invoke as \`agent: ${name}\``).join('\n')
      : '_No personas installed. Run harness init with matching skills or `harness sync`._';

  const hasHarness = pathExists(root, HARNESS_ROOT);
  const archRulesNote = hasHarness
    ? `**Before implementation, read \`.nextstage-harness/rules/architecture-rules.md\`.** If still the harness stub, run \`architecture-rules-generator\` then \`npx @nextstage-brasil/harness sync\`.`
    : '**Harness rules not scaffolded** — run `harness init` or `harness migrate-rules`.';

  const content = `# Project agents — ${projectName}

NextStage harness project. Skills detected from \`.agents/skills/\` (generated by CLI — refine with \`agents-md-generator\` skill for brownfield).

${archRulesNote}

${GENERATED_MARKER}
${syncManaged}

## Product anchor

| Variable | Value |
| -------- | ----- |
| \`{product_root}\` | \`${root}\` |
| \`{harness_root}\` | \`${hasHarness ? harnessRoot : 'not present'}\` |

## Layout

| Path | Purpose | Status |
| ---- | ------- | ------ |
${layoutRows.join('\n')}

## Installed skills

${skillsList}

## Agent personas (subagents)

${personasBlock}

## Workflows

### SDD planning chain

${buildSddChain(installed)}

### Implementation

${buildImplementationNote(installed)}

### Brownfield / context

| Artifact | Path | Skill |
| -------- | ---- | ----- |
| Architecture constitution | \`.nextstage-harness/rules/architecture-rules.md\` | \`architecture-rules-generator\` |
| Brownfield map | \`docs/context/brownfield-map.md\` | \`bootstrap-brownfield\` |
| Business reverse spec | \`docs/context/system-reverse-spec.md\` | \`codebase-reverse-spec\` |

## Rules and sync

- Canonical rules: \`.nextstage-harness/rules/*.md\`
- Regenerate adapters: \`npx @nextstage-brasil/harness sync\`
- Refresh this file: \`npx @nextstage-brasil/harness agents-md\`
- Personas: \`.agents/agents/\` → symlinks in \`.cursor/agents/\`, \`.claude/agents/\`

See \`nextstage-harness\` skill (\`harness-discovery.md\`, \`rules-sync.md\`).

## Language

Project code comments and documentation: English unless the team defines otherwise.

`;

  writeFileSync(agentsPath, content, 'utf8');
  writeFileSync(claudePath, '@AGENTS.md\n', 'utf8');

  return {
    skipped: false,
    written: ['AGENTS.md', 'CLAUDE.md'],
    skills: installed,
    personas,
  };
}
