const BROWNFIELD_SKILLS = new Set(['bootstrap-brownfield']);

export function buildPostInstallNotes({
  preset,
  installedSkills = [],
  projectRoot,
  scaffoldRan = true,
  noScaffold = false,
}) {
  const lines = [];
  const productRoot = projectRoot || process.cwd();
  const isBrownfield =
    preset === 'brownfield' ||
    installedSkills.some((skill) => BROWNFIELD_SKILLS.has(skill));
  const isExistingPreset = ['recommended', 'gitlab', 'implementation', 'brownfield'].includes(
    preset,
  );

  if (!noScaffold && scaffoldRan) {
    lines.push('AGENTS.md + CLAUDE.md generated by harness (from installed skills).');
    lines.push('');
    lines.push('Next steps — run in your AI agent when you have a real codebase:');
    lines.push('');
    lines.push('1. Architecture rules (technical constitution)');
    lines.push('   Skill: architecture-rules-generator');
    lines.push(
      `   Prompt: "Scan this codebase and generate architecture-rules.md for ${productRoot}. Then run harness sync."`,
    );
    lines.push('   Output: .nextstage-harness/rules/architecture-rules.md');
    lines.push('   Then:  npx @nextstage-brasil/harness sync');
    lines.push('');

    if (isBrownfield) {
      lines.push('1.5 Brownfield map (SDD planning input)');
      lines.push('    Skill: bootstrap-brownfield');
      lines.push(
        `    Prompt: "Bootstrap brownfield analysis for ${productRoot} before we plan version 1.0."`,
      );
      lines.push('    Output: docs/context/brownfield-map.md');
      lines.push('');
    }

    lines.push('2. Business reverse spec (optional)');
    lines.push('   Skill: codebase-reverse-spec');
    lines.push(
      '   Prompt: "Reverse-engineer this codebase into a technology-agnostic system description. Save to docs/context/system-reverse-spec.md"',
    );
    lines.push('   Output: docs/context/system-reverse-spec.md');
    lines.push('');
    lines.push('Optional: skill agents-md-generator — refine AGENTS.md with project context (brownfield).');
    lines.push('Refresh CLI baseline: npx @nextstage-brasil/harness agents-md --force');
    lines.push('New project rules: npx @nextstage-brasil/harness add-rule <name> (see .nextstage-harness/README.md)');

    if (isExistingPreset) {
      lines.push('');
      lines.push('Skip steps 1–2 if greenfield with no code yet.');
    }

    lines.push('');
    lines.push(
      'Order (existing codebases): architecture-rules-generator → bootstrap-brownfield → codebase-reverse-spec → clarify-requirements',
    );
  } else {
    lines.push('Skills installed. Run: npx @nextstage-brasil/harness agents-md');
    lines.push('Full guide: packages/harness/docs/README_INSTALLER.md');
  }

  lines.push('');
  lines.push('SDD chain: clarify-requirements → requirements-generator → task-generator → code-coder → code-reviewer');

  return lines.join('\n');
}
