/**
 * Shared rule body helpers (leaf module — no import from syncRules/absorb).
 */

export const GENERATION_MARKER =
  '<!-- generated by @nextstage-brasil/harness sync — do not edit -->';
export const RULE_BODY_ONLY_HINT =
  '<!-- harness-rule: body only — edit cursor.alwaysApply and cursor.description in .nextstage-harness/manifest.json; run harness sync after. Do not put YAML apply metadata in this file. -->';
const RULE_BODY_ONLY_HINT_RE = /<!--\s*harness-rule:\s*body only[\s\S]*?-->/;
const RULE_BODY_ONLY_HINT_STRIP_RE = /<!--\s*harness-rule:\s*body only[\s\S]*?-->\s*/g;

export const HASH_PATTERN = /<!-- harness-sync:sha256=([a-f0-9]+) -->/;

export function stripFrontmatter(content) {
  if (!content.startsWith('---\n')) {
    return content;
  }
  const end = content.indexOf('\n---\n', 4);
  if (end === -1) {
    return content;
  }
  return content.slice(end + 5);
}

export function hasRuleBodyHint(body) {
  return RULE_BODY_ONLY_HINT_RE.test(body);
}

/** Prepend body-only hint when missing (canonical files only). */
export function ensureRuleBodyHint(body) {
  const trimmed = body.trimStart();
  if (hasRuleBodyHint(trimmed)) {
    return trimmed.endsWith('\n') ? trimmed : `${trimmed}\n`;
  }
  return `${RULE_BODY_ONLY_HINT}\n\n${trimmed}`;
}

/** Strip body-only hint from adapter output (final Cursor/Claude rules). */
export function stripRuleBodyHint(body) {
  const stripped = body.replace(RULE_BODY_ONLY_HINT_STRIP_RE, '').trimStart();
  return stripped.endsWith('\n') || stripped.length === 0 ? stripped : `${stripped}\n`;
}

/**
 * Strip generation markers / hash comments / body-only hint before canonicalizing.
 * @param {string} body
 */
export function stripAdapterNoise(body) {
  let text = body;
  const marker = GENERATION_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  text = text.replace(new RegExp(`${marker}\\s*`, 'g'), '');
  text = text.replace(new RegExp(`${HASH_PATTERN.source}\\s*`, 'g'), '');
  return stripRuleBodyHint(text);
}
