import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { HARNESS_ROOT } from './agentsLayout.js';

export const GENERATION_MARKER =
  '<!-- generated by @nextstage-brasil/harness sync — do not edit -->';
export const HASH_PATTERN = /<!-- harness-sync:sha256=([a-f0-9]+) -->/;
export const SYNC_MANAGED_PATTERN =
  /<!-- harness-sync-managed: last-sync=[^>]+ -->/;

export function stripFrontmatter(content) {
  if (!content.startsWith('---\n')) {
    return content;
  }
  const end = content.indexOf('\n---\n', 4);
  if (end === -1) {
    return content;
  }
  return content.slice(end + 5);
}

export function hashBody(body) {
  return createHash('sha256').update(body.trimEnd(), 'utf8').digest('hex');
}

function buildCursorFrontmatter(rule) {
  const cursor = rule.cursor ?? {};
  const lines = ['---'];
  if (cursor.description) {
    lines.push(`description: ${cursor.description}`);
  }
  if (cursor.alwaysApply) {
    lines.push('alwaysApply: true');
  }
  if (cursor.globs) {
    lines.push(`globs: ${cursor.globs}`);
  }
  lines.push('---');
  return `${lines.join('\n')}\n`;
}

function buildClaudeFrontmatter(rule) {
  const paths = rule.claude?.paths;
  if (paths == null) {
    return '';
  }
  const lines = ['---', 'paths:'];
  for (const path of paths) {
    lines.push(`  - ${path}`);
  }
  lines.push('---');
  return `${lines.join('\n')}\n`;
}

export function buildAdapterBody(body, hash) {
  const trimmed = body.trimStart();
  return `${GENERATION_MARKER}\n<!-- harness-sync:sha256=${hash} -->\n\n${trimmed}`;
}

export function buildCursorAdapter(rule, body, hash) {
  return `${buildCursorFrontmatter(rule)}${buildAdapterBody(body, hash)}`;
}

export function buildClaudeAdapter(rule, body, hash) {
  return `${buildClaudeFrontmatter(rule)}${buildAdapterBody(body, hash)}`;
}

export function readAdapterHash(adapterContent) {
  const match = adapterContent.match(HASH_PATTERN);
  return match?.[1] ?? null;
}

export function updateAgentsSyncMarker(projectRoot, timestamp = new Date().toISOString()) {
  const agentsPath = join(projectRoot, 'AGENTS.md');
  if (!existsSync(agentsPath)) {
    return;
  }
  const marker = `<!-- harness-sync-managed: last-sync=${timestamp} -->`;
  const content = readFileSync(agentsPath, 'utf8');
  if (SYNC_MANAGED_PATTERN.test(content)) {
    writeFileSync(agentsPath, content.replace(SYNC_MANAGED_PATTERN, marker), 'utf8');
    return;
  }
  if (content.includes('<!-- harness-sync-managed:')) {
    return;
  }
}

export function syncRules(projectRoot, options = {}) {
  const {
    agents = ['cursor', 'claude-code'],
    check = false,
    updateAgentsMarker = !check,
  } = options;

  const harnessRoot = join(projectRoot, HARNESS_ROOT);
  const manifestPath = join(harnessRoot, 'manifest.json');

  if (!existsSync(manifestPath)) {
    throw new Error(
      `Missing ${HARNESS_ROOT}/manifest.json — run harness init or scaffold first`,
    );
  }

  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  if (!Array.isArray(manifest.rules)) {
    throw new Error('Invalid manifest: rules array required');
  }

  const drifts = [];
  const written = [];

  for (const rule of manifest.rules) {
    const canonicalPath = join(harnessRoot, rule.canonical);
    if (!existsSync(canonicalPath)) {
      throw new Error(`Canonical rule missing: ${rule.canonical}`);
    }

    const raw = readFileSync(canonicalPath, 'utf8');
    const body = stripFrontmatter(raw);
    const hash = hashBody(body);

    if (agents.includes('cursor')) {
      const adapterPath = join(projectRoot, '.cursor', 'rules', `${rule.name}.mdc`);
      const expected = buildCursorAdapter(rule, body, hash);
      if (check) {
        if (!existsSync(adapterPath)) {
          drifts.push(adapterPath);
        } else {
          const current = readFileSync(adapterPath, 'utf8');
          const currentHash = readAdapterHash(current);
          if (currentHash !== hash) {
            drifts.push(adapterPath);
          }
        }
      } else {
        mkdirSync(join(projectRoot, '.cursor', 'rules'), { recursive: true });
        writeFileSync(adapterPath, expected, 'utf8');
        written.push(adapterPath);
      }
    }

    if (agents.includes('claude-code')) {
      const adapterPath = join(projectRoot, '.claude', 'rules', `${rule.name}.md`);
      const expected = buildClaudeAdapter(rule, body, hash);
      if (check) {
        if (!existsSync(adapterPath)) {
          drifts.push(adapterPath);
        } else {
          const current = readFileSync(adapterPath, 'utf8');
          const currentHash = readAdapterHash(current);
          if (currentHash !== hash) {
            drifts.push(adapterPath);
          }
        }
      } else {
        mkdirSync(join(projectRoot, '.claude', 'rules'), { recursive: true });
        writeFileSync(adapterPath, expected, 'utf8');
        written.push(adapterPath);
      }
    }
  }

  if (!check && updateAgentsMarker) {
    updateAgentsSyncMarker(projectRoot);
  }

  return {
    ok: drifts.length === 0,
    drifts,
    written,
    check,
  };
}
