/** Canonical agent HTTP / SSE error codes. */

export const AGENT_ERROR = {
  LATENCY_BUDGET: "AGENT-LATENCY-BUDGET",
  CLIENT_CANCEL: "AGENT-CLIENT-CANCEL",
  LLM_FAILURE: "AGENT-LLM-FAILURE",
  INTERNAL: "AGENT-INTERNAL",
  HITL_APPROVER_REQUIRED: "AGENT-HITL-APPROVER-REQUIRED",
} as const;

export type AgentErrorCode =
  (typeof AGENT_ERROR)[keyof typeof AGENT_ERROR];
